#!/bin/bash
#PBS -S /bin/bash

## I want 1 processor only
#PBS -l procs=1

## How much RAM does each processor need?
#PBS -l pmem=2000mb

## The maximum walltime that will be used for my job 
#PBS -l walltime=00:15:00

## I want email sent when the job begins, ends and aborts (bea)
#PBS -m bea

## Where I want the email to be sent
#PBS -M prichmond@cmmt.ubc.ca


#Environmental variable defined by the batch system
cd $PBS_O_WORKDIR

echo "This is a job script"
date


