#!/bin/bash
#PBS -S /bin/bash

## I want 8 processors 
#PBS -l procs=12

## How much RAM does each processor need?
#PBS -l pmem=2000mb

## The maximum walltime that will be used for my job 
#PBS -l walltime=200:15:00

## I want email sent when the job begins, ends and aborts (bea)
#PBS -m bea

## Where I want the email to be sent
#PBS -M phillip.a.richmond@gmail.com

## Let's run this job from the place that we submit the script from 
cd $PBS_O_WORKDIR

## Define variables to be used in the commands below
WORKING_DIR='/global/scratch/ARC_Training/Session4/Files/PROCESS/'
GENOME='/global/scratch/ARC_Training/Session4/Files/GENOME/genome.fa'
FASTQR1='/global/scratch/ARC_Training/Session4/Files/RAW_DATA/SRR098401_1.fastq.gz'
FASTQR2='/global/scratch/ARC_Training/Session4/Files/RAW_DATA/SRR098401_2.fastq.gz'
SAM='NA12878_exome_bwa.sam'
BAM='NA12878_exome_bwa.bam'
SORTEDBAM='NA12878_exome_bwa.sorted'
SAMPLE_ID='NA12878_exome'

## Load the module containing bwa and samtools
module load bio-tools

## Let's go to directory we want to work in
cd $WORKING_DIR

## Generate BWA index (I already did this for you since it takes a long time)
## But if you want to know how to do it, it's simple:
#bwa index <in.fasta>
#bwa index $GENOME

## Map with BWA
#bwa mem -t 12  $GENOME \
#$FASTQR1 $FASTQR2 \
#-R "@RG\tID:$SAMPLE_ID\tSM:$SAMPLE_ID\tPL:illumina" \
#> $WORKING_DIR$SAM

## Convert sam to bam using samtools view
#samtools view -@ 12 -b $WORKING_DIR$SAM -o $WORKING_DIR$BAM 

## Sort the bam file using samtools sort
samtools sort  -m 2G $WORKING_DIR$BAM $WORKING_DIR$SORTEDBAM 

## Index the sorted bam 
samtools index $WORKING_DIR$SORTEDBAM  


